server:
  port: 10000

spring:
  application:
    name: member-service-provider-10000 #配置应用的名称
#  #配置sleuth 和 zipkin
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      #采样率 在0-1之间, 1表示全部采集
#      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/e_commerce_center_db?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml #指定mapper.xml文件位置
  type-aliases-package: com.springcloud.entity # 实例类所在的包,这样通过类名就可以引用

#配置eureka-client
eureka:
  client:
    register-with-eureka: true #将自己注册到Eureka-Server
    #表示从Eureka-Server 抓取注册信息
    #如果是单节点，是可以不配置的，但是如果是一个集群，则必须配置true,
    #才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #表示将自己注册到哪个eureka-server
      #将本微服务注册到多个eureka-server ,使用逗号间隔即可
      defaultZone: http://localhost:9001/eureka
#  instance:
#    #客户端向服务端发送心跳的时间间隔 1s(默认是30)
#    lease-renewal-interval-in-seconds: 1
#    #服务端收到最后一次心跳后等待的时间上限
#    #时间单位(秒)，默认是90s, 超时将剔除服务
#    lease-expiration-duration-in-seconds: 2
