server:
  port: 80
#配置eureka-client

spring:
  application:
    name: member-service-consumer-80 #配置应用的名称

eureka:
  client:
    register-with-eureka: true #将自己注册到Eureka-Server
    #表示从Eureka-Server 抓取注册信息
    #如果是单节点，是可以不配置的，但是如果是一个集群，则必须配置true,
    #才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #表示将自己注册到哪个eureka-server
      #将本微服务注册到多个eureka-server ,使用逗号间隔即可
      defaultZone: http://localhost:9001/eureka
#  instance:
#    #客户端向服务端发送心跳的时间间隔 1s(默认是30)
#    lease-renewal-interval-in-seconds: 1
#    #服务端收到最后一次心跳后等待的时间上限
#    #时间单位(秒)，默认是90s, 超时将剔除服务
#    lease-expiration-duration-in-seconds: 2
